In [2]:
# Q1.
import pandas as pd 

data = [4, 8, 15, 16, 23, 42]

In [2]:
data

[4, 8, 15, 16, 23, 42]

In [6]:
series= pd.Series(data)

In [7]:
series

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

In [49]:
# Q2.
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [50]:
list_ten = pd.Series(my_list)

In [52]:
print(list_ten)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [14]:
#Q3.
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Claire','moned'],
        'Age': [25, 30, 27,34],
        'Gender': ['Female', 'Male', 'Female','male']}

In [15]:
dataframe = pd.DataFrame(data)

In [16]:
dataframe

     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   27  Female
3   moned   34    male

In [17]:
dataframe['Age']

0    25
1    30
2    27
3    34
Name: Age, dtype: int64

In [18]:
type(dataframe)

pandas.core.frame.DataFrame

In [62]:
# #Q4.
# A DataFrame in Pandas is a 2-dimensional labeled data structure with columns of potentially different types. It is similar
# to a spreadsheet or SQL table, where each column represents a different variable or feature, and each row represents an
# observation or record. You can think of a DataFrame as a collection of Series objects that share the same index.

# A Series, on the other hand, is a one-dimensional labeled array that can hold any data type. It can be thought of as a 
# single column of a DataFrame.

In [19]:
# example: for my previous question 3 example for series
type(dataframe['Age'])

pandas.core.series.Series

In [20]:
# example: for my previous question 3 example for dataframe
type(dataframe)

pandas.core.frame.DataFrame

In [25]:
#Q5.
# Pandas provides a wide range of functions for manipulating data in a DataFrame. Here are some common functions and their usage:
data_csv = pd.read_csv("services.csv")

In [27]:
# head() and tail(): To view the first or last few rows of a DataFrame
data_csv.head()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [29]:
data_csv.tail()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [36]:
#Counting the rows and columns in DataFrame using shape(). It returns the no. of rows and columns enclosed in a tuple
data_csv.shape

(23, 22)

In [34]:
#Summary of Statistics of DataFrame using describe() method.
data_csv.describe()

             id  location_id  program_id
count  23.00000    23.000000         0.0
mean   12.00000    11.956522         NaN
std     6.78233     6.711444         NaN
min     1.00000     1.000000         NaN
25%     6.50000     6.500000         NaN
50%    12.00000    12.000000         NaN
75%    17.50000    17.500000         NaN
max    23.00000    22.000000         NaN

In [38]:
# info(): To display information about the DataFrame, such as its data types and number of non-null values. For example:
data_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       23 non-null     int64
 1   location_id              23 non-null     int64
 2   program_id               0 non-null      float64
 3   accepted_payments        1 non-null      object
 4   alternate_name           1 non-null      object
 5   application_process      23 non-null     object
 6   audience                 14 non-null     object
 7   description              23 non-null     object
 8   eligibility              21 non-null     object
 9   email                    1 non-null      object
 10  fees                     21 non-null     object
 11  funding_sources          21 non-null     object
 12  interpretation_services  1 non-null      object
 13  keywords                 21 non-null     object
 14  languages                1 non-null      object
 15  name                     23 non-null     object
 16  required_documents       1 non-null      object
 17  service_areas            21 non-null     object
 18  status                   23 non-null     object
 19  wait_time                19 non-null     object
 20  website                  2 non-null      object
 21  taxonomy_ids             1 non-null      object
dtypes: float64(1), int64(2), object(19)
memory usage: 4.1+ KB

In [42]:
# dropna(): To remove rows with missing values. For example:
data_csv.dropna()

Empty DataFrame
Columns: [id, location_id, program_id, accepted_payments, alternate_name, application_process, audience, description, eligibility, email, fees, funding_sources, interpretation_services, keywords, languages, name, required_documents, service_areas, status, wait_time, website, taxonomy_ids]
Index: []

[0 rows x 22 columns]

In [44]:
# fillna(): To replace missing values with a specified value or method. For example:
data_csv.fillna(4)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,4.0,4,4,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",4,...,4,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",4,Fair Oaks Adult Activity Center,4,Colma,active,No wait.,4,4
1,2,2,4.0,4,4,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",4,...,4,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",4,Second Career Employment Program,4,San Mateo County,active,Varies.,4,4
2,3,3,4.0,4,4,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,4,...,4,"Geriatric Counseling, Older Adults, Gay, Lesbi...",4,Senior Peer Counseling,4,San Mateo County,active,Varies.,4,4
3,4,4,4.0,4,4,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,4,...,4,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",4,Family Visitation Center,4,San Mateo County,active,No wait.,4,4
4,5,5,4.0,4,4,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,4,...,4,"COMMUNITY SERVICES, Speakers, Automobile Loans",4,Economic Self-Sufficiency Program,4,San Mateo County,active,4,4,4
5,6,6,4.0,4,4,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,4,...,4,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",4,Little House Recreational Activities,4,San Mateo County,active,No wait.,4,4
6,7,7,4.0,4,4,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,4,...,4,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",4,Rosener House Adult Day Services,4,"Belmont, Burlingame, East Palo Alto",active,No wait.,4,4
7,8,8,4.0,4,4,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,4,...,4,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",4,Meals on Wheels - South County,4,"Belmont, East Palo Alto",active,No wait.,4,4
8,9,9,4.0,4,4,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,4,...,4,"EDUCATION SERVICES, Library, Libraries, Public...",4,Fair Oaks Branch,4,San Mateo County,active,No wait.,4,4
9,10,10,4.0,4,4,Walk in. Proof of California residency to rece...,4,"Provides general reading and media materials, ...",Resident of California to obtain a card,4,...,4,"EDUCATION SERVICES, Library, Libraries, Public...",4,Main Library,4,San Mateo County,active,No wait.,4,4
10,11,11,4.0,4,4,Walk in. Proof of California residency require...,4,"Provides general reading materials, including ...",Resident of California to obtain a library car...,4,...,4,"EDUCATION SERVICES, Library, Libraries, Public...",4,Schaberg Branch,4,San Mateo County,active,No wait.,4,4
11,12,12,4.0,4,4,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,4,...,4,"EDUCATION SERVICES, Adult, Alternative, Litera...",4,Project Read,4,Daly City,active,Depends on availability of tutors for small gr...,4,4
12,13,13,4.0,4,4,Walk in. Proof of California residency require...,4,"Provides general reading materials, including ...",Resident of California to obtain a library card,4,...,4,"EDUCATION SERVICES, Library, Libraries, Public...",4,Redwood Shores Branch,4,San Mateo County,active,No wait.,4,4
13,14,14,4.0,4,4,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,4,...,4,"COMMUNITY SERVICES, Interpretation/Translation...",4,Redwood City Corps,4,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,4,4
14,15,15,4.0,4,4,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",4,...,4,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",4,Adult Rehabilitation Center,4,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,4,4
15,16,16,4.0,4,4,"Walk in. Written application, identification r...",4,Provides emergency assistance including food a...,None for emergency assistance,4,...,4,"COMMODITY SERVICES, Clothing/Personal Items, C...",4,Sunnyvale Corps,4,4,active,No wait.,4,4
16,17,17,4.0,4,4,Call for information.,4,"Provides emergency food, clothing and furnitur...",Low-income families,4,...,4,"COMMODITY SERVICES, Clothing/Personal Items, C...",4,South San Francisco Citadel Corps,4,"Colma, Daly City, South San Francisco",active,4,4,4
17,18,18,4.0,4,4,Call for screening appointment. Medical visits...,4,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,4,...,4,"HEALTH SERVICES, Outpatient Care, Community Cl...",4,Project Smile,4,East Palo Alto,active,Varies.,4,4
18,19,19,4.0,4,4,Call for screening appointment (650-347-3648).,4,Provides free medical and dental care to those...,Low-income person without access to health care,4,...,4,"HEALTH SERVICES, Outpatient Care, Community Cl...",4,San Mateo Free Medical Clinic,4,"Belmont, Burlingame",active,Varies.,4,4
19,20,20,4.0,4,4,Walk in.,4,no unrequired fields for this service,4,4,...,4,4,4,Service with blank fields,4,4,defunct,4,4,4
20,21,21,4.0,4,4,By phone during business hours.,4,just a test service,4,4,...,4,4,4,Service for Admin Test Location,4,San Mateo County,inactive,4,4,4
21,22,22,4.0,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,4.0,4,4,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,4,...,4,"Ruby on Rails/Postgres/Redis, testing, wic",4,Example Service Name,4,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,4

In [54]:
# groupby(): To group the DataFrame by one or more columns and apply a function to each group. For example
data_csv.groupby('alternate_name').mean()

/tmp/ipykernel_91/4289057251.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data_csv.groupby('alternate_name').mean()

                         id  location_id  program_id
alternate_name
Fotos para pasaportes  22.0         22.0         NaN

In [55]:
# #Q6.
# In Pandas, both Series and DataFrame are mutable in nature, meaning that their values can be changed after they are 
# created. For example, you can add, remove or modify rows and columns in a DataFrame, or change the values in a Series.

In [15]:
#Q7.

names = ['imtiyaz','ali','irfan','ajaz','hanifa','shujat']
professions=['developer','sales','marketting','hr','manager','co']
Age= [25, 30, 27,34]
Gender= ['Male', 'Male', 'Male','male']

name_list = pd.Series(names)
professions_list = pd.Series(professions)
Age_list = pd.Series(Age)
Gender_list = pd.Series(Gender)

In [16]:
type(name_list)

pandas.core.series.Series

In [17]:
dataframe= pd.DataFrame({"name":name_list,"profession":professions_list,"Age":Age_list,"Gender":Gender_list})

In [18]:
dataframe

      name  profession   Age Gender
0  imtiyaz   developer  25.0   Male
1      ali       sales  30.0   Male
2    irfan  marketting  27.0   Male
3     ajaz          hr  34.0   male
4   hanifa     manager   NaN    NaN
5   shujat          co   NaN    NaN

In [ ]:
type(dataframe)

In [ ]:
len